# -*- coding: utf-8 -*-
"""Setup

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBben9i2dpBW-G7V_2u3Q20cfOmwns6a
"""

from setuptools import setup

setup(
    name='your_app_name',
    version='0.1',
    install_requires=[
        'streamlit',
        'numpy',
        'pandas',
        'matplotlib',
        'scipy',
        'wheel',
    ],
)